#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 17 15:20:46 IST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_timer_led_behav -key {Behavioral:sim_1:Functional:tb_top_timer_led} -tclbatch tb_top_timer_led.tcl -view /home/pradeepjairam/ramanujamIP/other_rnd/fpga_demo_escalator/timer_DC/timer/synth/project_1/timer_led_behav.wcfg -log simulate.log"
xsim tb_top_timer_led_behav -key {Behavioral:sim_1:Functional:tb_top_timer_led} -tclbatch tb_top_timer_led.tcl -view /home/pradeepjairam/ramanujamIP/other_rnd/fpga_demo_escalator/timer_DC/timer/synth/project_1/timer_led_behav.wcfg -log simulate.log

