#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jul 15 18:38:53 IST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_traffic_light_cntrl_behav -key {Behavioral:sim_1:Functional:tb_traffic_light_cntrl} -tclbatch tb_traffic_light_cntrl.tcl -view /home/sinoradaniels/pulpino/git/traffic_light/synth/project_1/tb_traffic_light_cntrl_behav.wcfg -log simulate.log"
xsim tb_traffic_light_cntrl_behav -key {Behavioral:sim_1:Functional:tb_traffic_light_cntrl} -tclbatch tb_traffic_light_cntrl.tcl -view /home/sinoradaniels/pulpino/git/traffic_light/synth/project_1/tb_traffic_light_cntrl_behav.wcfg -log simulate.log

